# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            NCDyson
tagline:          'A Dev-Blog or something'
description:      'Project updates.'
url:              http://ncdyson.github.io
baseurl:          /

author:
  name:           'NCDyson'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
